name: MinGW

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - feature/*
    paths-ignore:
      - '**/*.md'
      - .gitignore
      - .editorconfig
      - appveyor.yml
      - 'azure-pipelines*.yml'
      - 'ci/azure-pipelines/template*.yml'

  pull_request:
    branches:
      - master
      - feature/*
      - release/*
    paths-ignore:
      - '**/*.md'
      - .gitignore
      - .editorconfig
      - appveyor.yml
      - 'azure-pipelines*.yml'
      - 'ci/azure-pipelines/template*.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: MinGW
    runs-on: windows-latest

    strategy:
      matrix:
        config:
          #- Debug
          - Release
        msystem:
          #- MINGW32
          - MINGW64

    steps:
    ## see https://github.com/actions/checkout
    - uses: actions/checkout@v2

    ## see https://github.com/msys2/setup-msys2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        path-type: inherit
        release: false

    - name: Build
      shell: msys2 {0}
      run: |
        cd sakura_core
        mingw32-make -j2 MYCFLAGS=--coverage MYLIBS=--coverage

    - name: Test
      shell: cmd
      run: |
        cd sakura_core
        start /wait sakura.exe "-M=InsText('a');FileSaveAs('x.txt');ExitAllEditors()" -MTYPE=js

    - name: Upload coverage
      shell: msys2 {0}
      run: |
        cd sakura_core
        bash <(curl -s https://codecov.io/bash)
